update
upgrade

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

install findutils

install bash

tap homebrew/dupes
install homebrew/dupes/grep

tap d12frosted/emacs-plus
install emacs-plus

install ack
install autojump
install coreutils
install erlang
install git
install heroku-toolbelt
install hub
install jq
install mas
install python
install reattach-to-user-namespace
install redis
install riak
install tmux
install tree
install vim
install wget
install zsh

# Install homebrew-cask

tap phinze/homebrew-cask
install brew-cask

# Install non appstore osx apps

cask --appdir="/Applications" \
  alfred \
  dropbox \
  google-drive \
  iterm2 \
  slate \
  spotify \
  sublime-text

# Install app store osx apps

mas 'LastPass', id: 926036361
mas 'Kindle', id: 405399194
mas 'Ulysses', id: 623795237
mas 'Chrono Plus', id: 946047238
mas 'Airmail 3', id: 918858936
mas 'Sketch', id: 425955336
mas 'Slack', id: 803453959
mas 'Dash', id: 458034879

# Remove outdated versions from the cellar

cleanup
